### ISSUE TITLE
sumologic_content error for config

### ISSUE THREAD

**Issue by brianabston001** [terraform-providers/terraform-provider-sumologic#22]
I am using the example on this page [https://www.terraform.io/docs/providers/sumologic/r/content.html](url) but I am seeing errors which is pointing to this Line 158. I am using the example straight from the example. 

config = 
    jsonencode({

Error: Invalid expression
On modules/application/sumo/config.tf line 158: Expected the start of an
expression, but found an invalid expression token.

Error: Argument or block definition required
On modules/application/sumo/config.tf line 159: An argument or block
definition is required here. To set an argument, use the equals sign "=" to
introduce the argument value.

I am using Terraform version v0.12.25

**Comment by brianabston001** [comment]
looks like the docs was wrong on the example following needs to be on the same line
config = 
    jsonencode({

Needs to be 
config = jsonencode({

**Comment by sumovishal** [comment]
@brianabston001 thanks for reporting and root causing the issue.  PR #23 will fix it.
