### ISSUE TITLE
[resource_sumologic_role]: No argument "users"

### ISSUE THREAD

**Issue by mlclmj** [terraform-providers/terraform-provider-sumologic#28]
The [argument reference](https://www.terraform.io/docs/providers/sumologic/r/role.html) seems to differ from the [actual resource schema](https://github.com/terraform-providers/terraform-provider-sumologic/blob/master/sumologic/resource_sumologic_role.go#L31):

```terraform
resource "sumologic_role" "example_role" {
  name        = "TestRole123"
  description = "Testing resource sumologic_role"

  filter_predicate = "_sourceCategory=Test"
  users = [
    "0000000000000001",
    "0000000000000002"
  ]
  capabilities = [
    "manageCollectors"
  ]
}
```

results in:
```terraform
Error: Unsupported argument

  on main.tf line 6, in resource "sumologic_role" "role":
   6:   users = []

An argument named "users" is not expected here.
```

**Comment by seansain** [comment]
Ya, that's right `users` is no longer an attribute of the `sumologic_role`. You specify the roles for each user in `sumologic_role`. I will update the documentation accordingly.
