### ISSUE TITLE
Make sumologic_polling_source and sumologic_cloudsyslog_source importable

### ISSUE THREAD

**Issue by hlhendy** [terraform-providers/terraform-provider-sumologic#36]
I noticed that only http sources are currently importable. If possible, can that be updated so all three can be imported?
https://github.com/terraform-providers/terraform-provider-sumologic/blob/master/sumologic/resource_sumologic_polling_source.go#L13-L16

https://github.com/terraform-providers/terraform-provider-sumologic/blob/master/sumologic/resource_sumologic_cloudsyslog_source.go#L12-L15

If not, it might be useful to have a note in the documentation for why that can't be done. 
https://www.terraform.io/docs/providers/sumologic/r/cloudsyslog_source.html

**Comment by vsinghal13** [comment]
@hlhendy thanks for requesting this. It will be available in the next release.

**Comment by hlhendy** [comment]
@vsinghal13 Thank you for making that change so quickly!
