### ISSUE TITLE
Feature Request: polling source import

### ISSUE THREAD

**Issue by mccartney** [terraform-providers/terraform-provider-sumologic#42]
I'd be great if the provider supported importing (`terraform import`) a polling source resource. Similar to what collectors do.
Currently it fails with:
```
Error: resource sumologic_polling_source doesn't support import
```

(I ended up manually hacking the state file)

**Comment by vsinghal13** [comment]
This feature request is already merged and will be available in the next release version.

**Comment by vsinghal13** [comment]
ref: https://github.com/terraform-providers/terraform-provider-sumologic/issues/36
