### ISSUE TITLE
Unable to observe or modify MetricsSavedSearchSyncDefinition content

### ISSUE THREAD

**Issue by jack-kearney** [terraform-providers/terraform-provider-sumologic#6]
Hello,

I've been having a lot of issues trying to use this provider to modify the `metricsQueries` field of a Sumo metric.

I've noticed that if another field has been changed, the provider can observe a change in the `metricsQueries` data. For instance, if I update the `metricsQueries` and `name` fields simultaneously the provider accurately determines that both fields have changed. However, if I update the `metricsQueries` without modifying the `name` field there are no proposed changes.

Any idea what might be happening here?

**Comment by sumovishal** [comment]
@jack-kearney I was able to reproduce the issue. Will try to fix it next week.

**Comment by seansain** [comment]
Thanks @jack-kearney for bring this up. Opened up a pull request with the fix.
