### ISSUE TITLE
Releases don't include assets

### ISSUE THREAD

**Issue by mmrobins** [terraform-providers/terraform-provider-sumologic#7]
Being able to download the precompiled provider from the assets for the release was very convenient in the old repo https://github.com/SumoLogic/terraform-provider-sumologic/releases.  Would be nice if that could be added to this new location

**Comment by seansain** [comment]
Hi Matt, since this is now an official provider, HashiCorp handles the release process for us. What was the use case for downloading the precompiled provider?

**Comment by mmrobins** [comment]
Ah, didn't realize this would work now without a manual install in `~/.terraform.d`.  Maybe the README section that says `To use the provider run make install in the root direcory to install it as a plugin` could be clearer that you can just declare the provider in your hcl to install it, and running `make install` is only necessary to install from local source code.

**Comment by seansain** [comment]
Thanks for the feedback! Will try to make the more clear.
